export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const REST_LOGIN_PAGE = 'REST_LOGIN_PAGE';
export const CHANGE_APP_STATE = 'CHANGE_APP_STATE';
export const UPDATE_CURRENT_USER_INFO = 'UPDATE_CURRENT_USER_INFO';
export const RESET_CURRENT_USER_INFO = 'RESET_CURRENT_USER_INFO';
export const LOGIN_PAGE_STATE_UPDATE = 'LOGIN_PAGE_STATE_UPDATE';
export const LOGIN_USER = 'LOGIN_USER';

export const LOGIN_USER_DONE = 'LOGIN_USER_DONE';

